#!/bin/bash -x
# Don't build in the QEMU source directory. Using a subdirectory is better.
# Here is an example of a debug build.

STR_PATH=$PWD

PKG_CONFIG_LIBDIR="C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\lib\pkgconfig"
C_INCLUDE_PATH="C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include:$STR_PATH\include"
CPLUS_INCLUDE_PATH="C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include:$STR_PATH\include" 
PATH="/cygdrive/c/cygwin64/bin":$PATH

BUILD_DIR=$STR_PATH/bin/debug/x86_64-w64-mingw64

mkdir -p $BUILD_DIR
cd $BUILD_DIR
$STR_PATH/configure --enable-debug  --disable-libusb --cc=x86_64-w64-mingw32-gcc.exe --cxx=x86_64-w64-mingw32-g++.exe  --cross-prefix=x86_64-w64-mingw32-  --target-list=arm-softmmu --disable-usb-redir
