#!/bin/bash -x
# Don't build in the QEMU source directory. Using a subdirectory is better.
# Here is an example of a debug build.

SRC_PATH=$PWD

PKG_CONFIG_LIBDIR="C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\lib\pkgconfig"
C_INCLUDE_PATH="C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include:$PWD\include"
CPLUS_INCLUDE_PATH="C:\cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw\include:$PWD\include" 
PATH="/cygdrive/c/cygwin64/bin":$PATH

BUILD_DIR=$PWD/bin/debug/x86_64-w64-mingw64

cd $BUILD_DIR



make

